echo off
rem Batch file to make .exe file automatically from .love file
rem ---
rem Output file name can be sent as %1 command-line argument,
rem default output file is bin\game.exe
rem ---
rem Requires make-love-file.bat
rem Requires love.exe file on bin\ folder

title Make Executable File
setlocal

rem Variables
set love_executable=bin\love.exe
set generated_love_file=bin\game.love

set file_name=%1
if "%1"=="" (set file_name=bin\game.exe)

rem Remove .exe file if it exists
if exist %file_name% (
    call rm %file_name%
)

rem Look for love.exe in bin\ folder
if not exist %love_executable% (
    echo love.exe file not found in bin folder!
    pause
    exit
)

call make-love-file.bat %generated_love_file%

rem Look for .love file on expected output location
if not exist %generated_love_file% (
    echo game.love file not found in bin folder!
    pause
    exit
)

echo ------

call copy /b "%love_executable%"+"%generated_love_file%"  "%file_name%"

rem Remove autogenerated .love file
call rm %generated_love_file%

echo Created %file_name%
