echo off
rem Batch file to package a love game for windows automatically
rem ---
rem Output file name can be sent as %1 command-line argument,
rem default output file is ninja_rush.zip
rem output is always located in bin\ folder
rem ---
rem Requires make-exe-file.bat
rem Requires love dlls file on bin\love-dlls folder

title Make Windows Package
setlocal

rem Variables
set love_dll_folder=bin\love-dlls\
set generated_exe_file=bin\love-dlls\ninja_rush.exe

set file_name=%1
if "%1"=="" (set file_name=ninja_rush.zip)

rem Remove .zip file if it exists
if exist bin\%file_name% (
    call rm bin\%file_name%
)

rem Look for love dlls filder in bin\ folder
if not exist %love_dll_folder% (
    echo love dll folder does not exist!
    pause
    exit
)

call make-exe-file.bat %generated_exe_file%

rem Look for .love file on expected output location
if not exist %generated_exe_file% (
    echo ninja_rush.exe file not found in bin folder!
    pause
    exit
)

echo ------

cd %love_dll_folder%
call 7z a -tzip %file_name% .
call mv %file_name% ..
cd ..\..\

rem Remove autogenerated .love file
call rm %generated_exe_file%

echo Created %file_name%
